__default__:
    partition: ibm_large
index_bam:
    partition: ibm_large
filter_avcf:
    cpus: 5
# CNVkit
cnvkit_access:
    cpus: 1
cnvkit_pipeline:
    partition: ibm_large
    cpus: 10
# FACETS
snp_pile:
    cpus: 5
    partition: ibm_large
facets:
    cpus: 5
    partition: ibm_large
# TitanCNA
correct_depth:
    cpus: 5
    partition: phi
read_counter:
    cpus: 5
    partition: phi
ichorCNA:
    cpus: 5
    partition: phi
getHETsites:
    cpus: 5
    partition: phi
getAlleleCountsByChr:
    cpus: 5
    partition: phi
catAlleleCountFiles:
    cpus: 5
    partition: phi
runTitanCNA:
    cpus: 5
    partition: phi
combineTitanAndIchorCNA:
    cpus: 5
    partition: phi
selectSolution:
    cpus: 5
    partition: phi
copyOptSolution:
    cpus: 5
    partition: phi
titan_clear_segfile:
    cpus: 5
    partition: phi
# ASCA sc
run_ascat_sc:
    cpus: 8
# phyloWGS
prepare_avcf:
    cpus: 5
parse_facets:
    cpus: 5
parse_titan:
    cpus: 5
pwgs_create_inputs:
    cpus: 5
pwgs_multievolve:
    partition: phi
    cpus: 20
pwgs_write_results:
    partition: phi
    cpus: 5
# sciClone
run_sciclone_facets:
    cpus: 5
# pyclone
pyclone_parse_tsv:
    cpus: 5
pyclone_setup_facets:
    cpus: 5
pyclone_setup_titan:
    cpus: 5
pyclone_setup_analysis:
    cpus: 5
pyclone_run_analysis:
    partition: phi
    cpus: 5
pyclone_build_cluster_table:
    partition: phi
    cpus: 5
pyclone_build_loci_table:
    partition: phi
    cpus: 5
pyclone_try_plot:
    partition: phi
    cpus: 5
pyclone_copy_results:
    partition: phi
    cpus: 5
