---
name: clonality
workdir: /scratch/scratch-hdd/pkus/workflows_results/clonality/Shlush_AML
manifest: /home/pkus/ngs_workflows/clonality_workflow/manifests/Shlush_AML.tsv

genomeBuild: "hg38"

## path to tools
samTools:  samtools
bcfTools:  bcftools


#####################################################
############################ CNVkit
#####################################################

genome_fa: /scratch/scratch-hdd/pkus/resources/hg38.fa
# targets_bed: /scratch/scratch-hdd/pkus/resources/agilent/Agilent_SureSelect_v6r2_S07604514_Covered_hg38.cnvkit.bed
targets_bed: /scratch/scratch-hdd/pkus/resources/agilent/Agilent_SureSelect_v6r2_S07604514_Covered_hg38.bed


#####################################################
############################ FACETS
#####################################################

FACETS_snp_vcf: "/scratch/scratch-hdd/pkus/resources/FACETS/hg38/00-common_all.chr.vcf.gz"

#####################################################
############################ ASCAT
#####################################################
# maybe one day
# ASCAT_loci: /scratch/scratch-hdd/pkus/resources/ASCAT/hg38/00-common_all.chr.loci


#####################################################
############################ TitanCNA
############################ Remember to set require appropriate genome package in workflow/envs/titancna_env.yml
#####################################################

## path to scripts ##
readCounterScript:  readCounter
ichorCNA_rscript:  /home/pkus/programs/ichorCNA-master/scripts/runIchorCNA.R
ichorCNA_libdir:  /home/pkus/programs/ichorCNA-master
pyCountScript:  /home/pkus/programs/TitanCNA-master/scripts/snakemake/code/countPysam.py
TitanCNA_rscript: /home/pkus/programs/TitanCNA-master/scripts/R_scripts/titanCNA.R
TitanCNA_combineTitanIchorCNA:  /home/pkus/programs/TitanCNA-master/scripts/snakemake/code/combineTITAN-ichor.R
TitanCNA_selectSolutionRscript: /home/pkus/programs/TitanCNA-master/scripts/R_scripts/selectSolution.R
TitanCNA_libdir:  #scripts/TitanCNA-master/R/

## reference settings and paths to reference files ##
# genomeBuild: hg19
genomeStyle:  UCSC
refFasta:  /home/pkus/resources/ucsc/hg19.fa
snpVCF: /home/pkus/resources/TitanCNA/hapmap_3.3.b37.chr.vcf.gz
ichorCNA_exons: null
cytobandFile:  null
centromere:  /home/pkus/programs/ichorCNA-master/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.chr.txt
# sex:  male   # use None if both females and males are in sample set ## now I use the one from samples.tsv file

## params for each step ##

## read depth params ##
# use this for NCBI chr naming
#chrs: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y 
# use this for UCSC chr naming
chrs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY 
binSize:  10000

## ichorCNA params ##
ichorCNA_gcWig: /home/pkus/programs/ichorCNA-master/inst/extdata/gc_hg19_10kb.wig
ichorCNA_mapWig:  /home/pkus/programs/ichorCNA-master/inst/extdata/map_hg19_10kb.wig
ichorCNA_chrs:  paste0(\"chr\", c(1:22, \"X\")) #c(1:22, \"X\")
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
ichorCNA_maxCN:  8
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)

## allele counts - samtools, pysam ##
# USERS MUST MODIFY getAlleleCounts.snakefile to use the correct CHRS naming
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
TitanCNA_maxNumClonalClusters: 2
TitanCNA_chrs:  paste0(\"chr\", c(1:22, \"X\")) #c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 3
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  10000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_numCores: 1

## Combine TitanCNA & ichorCNA
mergeIchorHOMD: FALSE  # consider setting to TRUE when working with pure tumor

...