name: BC_rna
---
name: rnaseq_smk
genome_fasta: /scratch/scratch-hdd/pkus/resources/rnaseq_files/gencode_mm_28/GRCm39.primary_assembly.genome.fa
star_genome_dir: /scratch/scratch-hdd/pkus/resources/star_genomes/gencode_mm_28_149
rseqc_ref: /scratch/scratch-hdd/pkus/resources/rnaseq_files/gencode_mm_28/mm28_RefSeq.bed
gtf_file: /scratch/scratch-hdd/pkus/resources/rnaseq_files/GRCh38.p13_gencode/gencode.v38.primary_assembly.annotation.gtf
sjdbOverhang: 149
...